# Generated by Django 4.2.1 on 2023-05-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarySys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
